require("config.after.colorscheme")
require("config.after.clipboard")
require("config.after.git")
require("config.after.treesitter")
require("config.after.telescope")
require("config.after.undotree")
require("config.after.ai")
require("config.after.todo")
